apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: asiayo
type: Opaque
stringData:
  root-password: "CHANGE_ME"
  database: "wordpress"
  username: "wordpress"
  password: "CHANGE_ME"
