apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: asiayo
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-writer
  namespace: asiayo
spec:
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: mysql-0
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-reader
  namespace: asiayo
spec:
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: mysql-1
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
